/**
 * Copyright 2022 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// This file is auto-generated by vscode-router-generator
// Do not edit this file directly

// Page Routes

import { customElement } from "lit/decorators.js";
import { css, html, LitElement, TemplateResult } from "lit";
import { renderRoute } from "./router.js";

@customElement("generated-app")
export class GeneratedApp extends LitElement {
  static styles = css`
    main {
      transition: opacity 0.3s ease-in-out;
    }
  `;

  template: TemplateResult | null = null;

  override render() {
    return html` <main>${this.template || html`Loading...`}</main> `;
  }

  override async firstUpdated() {
    window.addEventListener("hashchange", () => this.updateRoute());
    this.updateRoute();
    const route = window.location.hash.slice(1);
    if (route === "" || route == "/") window.location.hash = "/start";
  }

  async updateRoute() {
    // Cross fade between pages
    document.body.style.opacity = "0";
    const route = window.location.hash.slice(1);
    const template = await renderRoute(route);
    this.template = template;
    await new Promise((resolve) => setTimeout(resolve, 150));
    document.body.style.opacity = "1";
    this.requestUpdate();
  }
}
